[theme]
primaryColor = "#007acc"  # Azure blue, common in IT/tech interfaces
backgroundColor = "#1e1e1e"  # Dark background common in code editors
secondaryBackgroundColor = "#2d2d2d"  # Slightly lighter than background
textColor = "#e0e0e0"  # Light grey for good contrast on dark background
font = "sans serif"